
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "0.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/gotnospirit/messageformat"

[[constraint]]
  branch = "master"
  name = "github.com/jacobsa/crypto"

[[constraint]]
  branch = "master"
  name = "github.com/smartystreets/assertions"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "^1.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/viper"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/pflag"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"
  source = "https://github.com/rvolosatovs/mapstructure.git"

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/go-grpc-middleware"

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[constraint]]
  branch = "master"
  name = "github.com/mohae/deepcopy"

[[constraint]]
  branch = "master"
  name = "github.com/kr/pretty"
