contact_links:
- name: Documentation Request
  url: https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/new
  about: Suggest an improvement to our documentation
- name: The Things Network Community Forum
  url: https://www.thethingsnetwork.org/forum/c/application-development/15
  about: Please ask and answer questions on the forum.
