extends:
  - ttn
  - plugin:jest/recommended

parser: babel-eslint

plugins:
  - jsdoc

env:
  node: true
  jest: true

globals:
  shallow: true
  render: true
  mount: true
  snapshotDiff: true

parserOptions:
  ecmaFeatures:
    # Remove after migration
    legacyDecorators: true

rules:
  jest/no-large-snapshots:
    - warn
    - maxSize: 400

  jsdoc/no-undefined-types: error
  jsdoc/check-param-names: error
  jsdoc/check-types: error
  jsdoc/require-param-name: error
  jsdoc/require-param-type: error
  jsdoc/require-hyphen-before-param-description: error

  # Warn on console occurrences
  no-console:
    - warn

  # Warn on missing JsDoc definitions
  valid-jsdoc:
    - warn
    - prefer:
        return: returns
        arg: param
        argument: param
        class: constructor
        virtual: abstract
      requireReturn: false
