# Example ttn-lw-stack configuration file

# Identity Server configuration
# is:
  # Email configuration for "thethings.example.com"
  # email:
    # sender-name: 'The Things Stack'
    # sender-address: 'noreply@thethings.example.com'
    # network:
    #   name: 'The Things Stack'
    #   console-url: 'https://thethings.example.com/console'
    #   identity-server-url: 'https://thethings.example.com/oauth'

    # If sending email with Sendgrid
    # provider: sendgrid
    # sendgrid:
    #   api-key: '...'              # enter Sendgrid API key

    # If sending email with SMTP
    # provider: smtp
    # smtp:
    #   address:  '...'             # enter SMTP server address
    #   username: '...'             # enter SMTP server username
    #   password: '...'             # enter SMTP server password

  # Web UI configuration for "thethings.example.com":
  # oauth:
  #   ui:
  #     canonical-url: 'https://thethings.example.com/oauth'
  #     is:
  #       base-url: 'https://thethings.example.com/api/v3'

# HTTP server configuration
# http:
#   cookie:
#     block-key: '...'                # generate 32 bytes (openssl rand -hex 32)
#     hash-key: '...'                 # generate 64 bytes (openssl rand -hex 64)
#   metrics:
#     password: 'metrics'               # choose a password
#   pprof:
#     password: 'pprof'                 # choose a password

# If using custom certificates:
tls:
  source: file
  root-ca: ./ca.pem
  certificate: ./cert.pem
  key: ./key.pem

# Let's encrypt for "thethings.example.com"
# tls:
#   source: 'acme'
#   acme:
#     dir: '/var/lib/acme'
#     email: 'you@thethings.example.com'
#     hosts: ['thethings.example.com']
#     default-host: 'thethings.example.com'

# If Gateway Server enabled, defaults for "thethings.example.com":
# gs:
#   mqtt:
#     public-address: 'thethings.example.com:1882'
#     public-tls-address: 'thethings.example.com:8882'
#   mqtt-v2:
#     public-address: 'thethings.example.com:1881'
#     public-tls-address: 'thethings.example.com:8881'

# If Gateway Configuration Server enabled, defaults for "thethings.example.com":
# gcs:
#   basic-station:
#     default:
#       lns-uri: 'wss://thethings.example.com:8887'
#   the-things-gateway:
#     default:
#       mqtt-server: 'mqtts://thethings.example.com:8881'

# Web UI configuration for "thethings.example.com":
# console:
#   ui:
#     canonical-url: 'https://thethings.example.com/console'
#     is:
#       base-url: 'https://thethings.example.com/api/v3'
#     gs:
#       base-url: 'https://thethings.example.com/api/v3'
#     ns:
#       base-url: 'https://thethings.example.com/api/v3'
#     as:
#       base-url: 'https://thethings.example.com/api/v3'
#     js:
#       base-url: 'https://thethings.example.com/api/v3'
#     qrg:
#       base-url: 'https://thethings.example.com/api/v3'
#     edtc:
#       base-url: 'https://thethings.example.com/api/v3'
#     dcs:
#       base-url: 'https://thethings.example.com/api/v3'
#
#   oauth:
#     authorize-url: 'https://thethings.example.com/oauth/authorize'
#     token-url: 'https://thethings.example.com/oauth/token'
#     client-id: 'console'
#     client-secret: 'console'          # choose or generate a secret
